@node Introduction
@chapter Introduction

@clostrophilia{} provides a complete implementation of the Common Lisp
object system.  The code is divided into several @asdf{} systems,
where each system contains code for some aspect of the specification
in the book ``The Art of the Metaobject Protocol''.

Since client code may want its own ways of representing standard
objects, @clostrophilia{} does not assume any particular
representation.  Instead, it requires client code to define functions
for allocating a standard object and for accessing the different parts
of such an object.

Contrary to other implementations of CLOS such as PCL,
@clostrophilia{} is not designed to be added to an existing pre-ANSI
implementation of @commonlisp{}.  Instead, it is designed to be
bootstrapped using an existing conforming implementation of
@commonlisp{}.
