\input texinfo

@settitle Clostrophilia, an implementation of the Common Lisp package system.

@titlepage
@title Clostrophilia documentation
@end titlepage

@contents

@macro clostrophilia{}
Clostrophilia
@end macro

@node Top
@top @clostrophilia{}

This document describes the implementation of @clostrophilia{}.

@menu
* Introduction:: What @clostrophilia{} provides and how.
* Index:: Complete index.
@end menu

@include chap-introduction.texi

@node Index
@unnumbered Index

@printindex cp

@bye
