\input texinfo

@settitle Clostrophilia, an implementation of the Common Lisp package system.

@titlepage
@title Clostrophilia documentation
@end titlepage

@contents

@include logos.texi

@node Top
@top @clostrophilia{}

This document describes the implementation of @clostrophilia{}.

@menu
* Introduction:: What @clostrophilia{} provides and how.
* Class initializatin:: Initialization of Class Metaobjects
* Index:: Complete index.
@end menu

@include chap-introduction.texi
@include chap-class-initialization.texi

@node Index
@unnumbered Index

@printindex cp

@bye
