clostrophilia.pdf: clostrophilia.texi logos.texi chap-introduction.texi chap-class-initialization.texi chap-generic-function-initialization.texi
	texi2pdf clostrophilia.texi

clean:
	rm -f *.aux *.toc *.log clostrophilia.pdf *~
